# Generated by Django 4.2.25 on 2025-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0002_category_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(upload_to='photos/category/'),
        ),
    ]
