# Generated by Django 4.2.25 on 2025-10-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0004_alter_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
