# Generated by Django 4.2.25 on 2025-10-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(auto_created=True, help_text='a label for URL config', max_length=200, unique=True)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=1000)),
                ('product_image', models.ImageField(upload_to='photos/products')),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_categories.category')),
            ],
        ),
    ]
