# Generated by Django 4.2.25 on 2025-10-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crops',
            field=models.TextField(help_text="e.g. 'Cereals, pulses, oilseeds, fruits, vegetables, flowers'", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.TextField(help_text="e.g. '100 g/pump, 1 kg/acre'", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.TextField(help_text="e.g. '1 kg, 25 kg'", null=True),
        ),
    ]
