# Generated by Django 4.2.25 on 2025-10-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_crops_product_dosage_product_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(blank=True, help_text='a label for URL config', max_length=200, unique=True),
        ),
    ]
